# Generated by Django 5.0.4 on 2024-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='types/types/')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('$', '$'), ('som', 'som')], default='som', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discounts/discounts/')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('discount_price', models.FloatField()),
                ('product', models.ManyToManyField(to='users.types')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('image', models.ImageField(upload_to='vegetables_new/vegetables_new/')),
                ('description', models.TextField()),
                ('price_type', models.CharField(choices=[('$', '$'), ('som', 'som')], default='som', max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('x_link', models.URLField(null=True)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('m_link', models.ManyToManyField(choices=[('$', '$'), ('som', 'som')], default='$', to='users.types')),
            ],
        ),
    ]
