# Generated by Django 5.0.4 on 2024-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('adres', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=20)),
                ('discount', models.TextField()),
                ('image', models.ImageField(upload_to='shop.html/shop.html/')),
                ('author', models.CharField(max_length=50)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('project', models.ManyToManyField(to='shops.magazin')),
            ],
        ),
    ]
